name: basismixer

channels:
  - defaults
  - torch

dependencies:
  - python=3.9
  - torch
  - numpy
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - pip
  - tqdm

  - pip:
    - appdirs
    - soundfile
    - partitura
